FEeasy404/GameUs

- src/components/atoms/Button/Button.jsx
- src/components/atoms/Button/Button.module.css
로그인에 들어가는 버튼 컴포넌트 생성. 다른 UI에서도 충분히 사용할 수 있도록 만들었습니다 #4 
멌진 버튼
> Feat: 버튼 컴포넌트 및 스타일시트 생성

- public/reset.css
- src/components/modules/LoginForm/LoginForm.jsx
- src/components/organisms/LoginPageForm/LoginPageForm.jsx
- src/index.js
- src/pages/JoinPage.jsx
- src/pages/LoginPage.jsx
#4
- 헤딩 + 로그인 폼 모듈을 올가니즘화 했습니다.
- 올가니즘을 이용하여 로그인 페이지와 회원 가입 페이지를 만들었습니다.
- 회원 가입 페이지에서 다음 버튼을 누르면 프로필 설정 페이지로 이동하도록 해야 합니다!
> Feature: 로그인 폼 올가니즘화 및 로그인, 회원가입 페이지 구현 #4

- src/components/atoms/SignInSignUp/SignInSignUp.jsx
- src/components/atoms/SignInSignUp/signInSignUp.module.css
- #4 
로그인, 회원가입 이동 링크 버튼을 생성하였습니다.
> Feat: 로그인, 회원가입 이동 링크 버튼 생성 #4

- src/components/atoms/ProfileImageInput/ProfileImageInput.jsx
- src/components/modules/ProfileForm/ProfileForm.jsx
- src/components/organisms/ProfileSetting/ProfileSetting.jsx
- src/pages/ProfileSettingPage.jsx
프로필 이미지 설정 컴포넌트, 프로필 폼, 프로필 설정 올가니즘 및 페이지를 생성했습니다.  #11
> 프로필 설정 페이지 생성

- src/App.js
- src/App.jsx
- src/components/organisms/LoginPageForm/LoginPageForm.jsx
max-width를 모든 페이지에 적용하기 위해 App.jsx에서 감싸주도록 변경했습니다.
App.js를 App.jsx로 바꾸었습니다!
> Design: .max-width wrapper를 App.jsx에서 감싸주도록 변경

- src/components/atoms/Image/Image.jsx
- src/components/atoms/Image/image.css
- src/components/atoms/Image/image.module.css
- #6, #7
- #8, #9, #10 
- #11, #13, #14 
- #12
등에 쓰일 이미지 파일 컴포넌트를 만들었습니다. 
https://sophiecial.tistory.com/32
- css 파일 주석에 이미지 용도를 적어놨어요.
- ~~아직은 반응형을 고려하지 않고 고정값으로 작업했는데, 나중에 필요하다면 반응형으로 고쳐보아요!~~
채팅창 이미지는 max-width, 게시글 이미지는 width: 100%로 설정했습니다. 상품 등록 페이지에 들어갈 이미지는 height 고정이 맞는 거 같아서 우선 그대로 두었어요
- ~~module.css가 안 먹혀서 그냥 css로 했어요... 수정하고 싶어요~~ 수정했습니다!
> Feature: Image 컴포넌트 및 스타일시트 생성

- src/components/modules/LoginForm/LoginForm.jsx
- src/components/modules/ProfileForm/ProfileForm.jsx
> Fix: InputBox 컴포넌트명 미변경 파일 수정

- src/components/atoms/Button/Button.jsx
- src/components/atoms/Button/button.module.css
#4 #17 #19
- button.css를 button.module.css로 변경
- 버튼이 a태그로 만들어질 경우 width: 100%와 중앙정렬이 적용되지 않는 문제 해결
- Button.jsx에 import되는 css를 module.css로 변경
- classList 배열에 빈 문자열이 들어가, className에 불필요한 공백이 들어가는 문제 해결
코드 가독성이 괜찮은지 확인해주세요!
> Button 컴포넌트 css 모듈화

- src/components/atoms/ImageBox/ImageBox.jsx
- src/components/atoms/ImageBox/imageBox.module.css
- #25 에서 만들었던 이미지 컴포넌트의 이름을 ImageBox로 변경했습니다.
- 가장자리가 둥근 사각형 이미지의 클래스 이름을 .squircle에서 .rounded_square로 변경했습니다.
> Rename: 이미지 파일 컴포넌트 이름 변경 및 클래스명 변경

- src/components/atoms/Button/button.module.css
- src/components/atoms/ImageBox/imageBox.module.css
- src/components/atoms/ImageInputButton/imageInputButton.module.css
- src/components/atoms/InputBox/inputBox.module.css
- src/components/atoms/SignInSignUp/signInSignUp.module.css
- src/components/atoms/UserInfo/userInfo.module.css
- src/components/atoms/UserNameIntroduce/userNameIntroduce.module.css
- src/components/modules/ImageInputForm/imageInputForm.module.css
- src/components/organisms/EmailPasswordForm/emailPasswordForm.module.css
- src/global.css
- src/pages/LoginPage/loginPage.module.css
- 많이 쓰이는 색상을 변수화했습니다.
- css 파일들의 색상 부분을 변수로 바꿔주었습니다.
- #fff는 white로, #000은 black으로 대체할 수 있어서 굳이 변수화하지 않았습니다
> Style: 색상 변수화 및 색상 변수를 css파일에 일괄 적용

- src/assets/icon-arrow-left.svg
- src/assets/icon-more-vertical.svg
- src/assets/icon-search.svg
- src/components/atoms/HeaderInput/HeaderInput.jsx
- src/components/atoms/HeaderInput/headerInput.module.css
- src/components/atoms/IconButton/IconButton.jsx
- src/components/atoms/IconButton/IconButton.module.css
- src/components/modules/HeaderForm/HeaderForm.jsx
- src/components/modules/HeaderForm/headerForm.module.css
- src/global.css
다양한 페이지에서 사용되는 헤더 모듈 컴포넌트를 생성하였습니다. 
```
<HeaderForm title="게임어스 피드" titleSize="large" searchButton={true}/>
<HeaderForm backButton={true} button="저장" />
<HeaderForm backButton={true} button="업로드" />
<HeaderForm backButton={true} Input={true} />
<HeaderForm backButton={true} title="Followers" titleSize="small"/>
<HeaderForm backButton={true} title="애월읍 위니브 게임랜드" titleSize="small" menuButton={true}/>
<HeaderForm backButton={true} menuButton={true} />
```
- **IconButton 컴포넌트**를 만들었습니다. 아이콘 버튼이 필요하신 분은, 이미지 파일 추가한후 이컴포넌트를 사용해주시면 될것 같습니다!
- 버튼 기능은 현재 뒤로가기 버튼만 작동합니다. 
- global.css에 whitegray색상을 추가하였습니다. 
- 헤더 모듈은, 필요한 컴포넌트에 true를 주어 조합하도록 하였습니다.
> Feat: Header 모듈 생성 

- src/components/modules/MyProfileButton/MyProfileButton.jsx
- src/components/modules/UserProfileBox/UserProfileBox.jsx
- src/pages/ProfilePage.jsx
- #11 에 판매중인 상품 리스트를 추가했습니다.
- #11 페이지 및 컴포넌트들에 헤딩 태그로 제목을 주고 ir기법으로 숨겨주었습니다.
- 상품 등록 버튼을 누르면 상품 등록 페이지에 연결되도록 했습니다.
> Feat: 판매중인 상품 부분을 프로필 페이지에 추가 및 프로필 페이지에 ir 텍스트 삽입

- package-lock.json
- src/assets/icon-more-vertical-small.svg
- src/components/atoms/Author/Author.jsx
- src/components/atoms/Author/author.module.css
- src/components/atoms/MoreButton/MoreButton.jsx
- src/components/atoms/MoreButton/moreButton.module.css
#3 의 게시글과 댓글에 사용되는 더보기 버튼을 만들었습니다.
#55 에서 저자 컴포넌트를 이미 만들었는데 중복되었습니다.
중복되는 내용은 충돌 해결하겠습니다!
> 게시글 카드 댓글 및 게시글에 사용되는 더보기 버튼 컴포넌트 생성

- src/App.jsx
- src/components/organisms/UserProfile/UserProfile.jsx
- src/pages/ProfilePage.jsx
- #11 에서 fetch를 이용하여 url에 주어지는 accountname의 계정 정보를 받아오도록 변경했습니다.
- https://velog.io/@wjd489898/ReactURL-%EC%A0%95%EB%B3%B4%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0matchuseParams
- 토큰이 로컬 스토리지에 저장되어 있어야 에러가 뜨지 않습니다!
> Feat: fetch를 사용하여 서버에서 프로필 데이터를 받아오도록 변경

- src/components/atoms/InputBox/InputBox.jsx
InputBox 컴포넌트 명이 변경이 안되어있는 오류가 있어 수정합니다.
> Fix: InputBox 컴포넌트명 미변경 재수정

- src/components/modules/ProfileForm/ProfileForm.jsx
- #12 에서 ProfileForm의 InputBox에 `placeholder`가 누락되어 있어 추가했습니다.
> Fix: ProfileForm의 InputBox 컴포넌트에 placeholder 추가

- src/App.jsx
- src/components/modules/MyProfileButton/MyProfileButton.jsx
- src/components/modules/ProfileForm/ProfileForm.jsx
- src/components/modules/ProfileForm/profileForm.module.css
- src/pages/ProfileEditPage.jsx
- #14 의 마크업 및 css를 구현했습니다.
- 프로필 페이지에서 프로필 수정 버튼을 누르면 이 페이지로 이동합니다.
- 프로필 수정 기능은 로그인 기능 구현 이후에 해보도록 하겠습니다...
> Feat: 프로필 수정 페이지 마크업 및 css 구현

- package-lock.json
- package.json
- src/App.jsx
- src/components/atoms/Button/button.module.css
- src/components/atoms/ImageInputButton/ImageInputButton.jsx
- src/components/atoms/InputBox/InputBox.jsx
- src/components/modules/HeaderForm/HeaderForm.jsx
- src/components/modules/ImageInputForm/ImageInputForm.jsx
- src/components/modules/ProductTextInput/ProductTextInput.jsx
- src/components/organisms/AddProduct/AddProduct.jsx
- src/pages/AddProductPage.jsx
- #8 
- 상품 이미지, 상품명, 가격, 판매링크를 입력받을 수 있으며, 모든 입력이 완료되면 저장 버튼이 활성화됩니다.
- 상품명은 2~15자 이내로 입력되게 하고, 가격은 숫자를 입력하면 자동으로 원단위로 변환시킵니다.
- 상품명 2~15 미입력시 실시간으로 하단에 오류 메세지가 뜹니다. 
- 가격에는 숫자가 아닌것을 입력하면 오류메세지가 뜹니다. 
- 정상적으로 입력되지 않았을 경우에는 저장 버튼이 활성화 되지 않습니다. 
- 정상적으로 입력이 끝났을 경우 저장버튼이 활성화 됩니다. 
- 저장 버튼을 누르면 계정 홈으로 돌아갑니다. 
- 판매 상품이 추가되었습니다. 
- 이미지를 원범님이 하셨던것 참고하여 서버에 보냈다가 url을 받아오는 방식으로 변경하였습니다. 
- ~~저장 버튼을 누르면 /profile/${accoutname} 경로로 이동해야 하는데, accoutname을 어디에서 받아와야 하는건지 몰라서~~ 
저장 버튼을 누르면 App.jsx에서 혜원님이 공유해 주신 계정인 weniv_Gameland로 연결해 놓았습니다. (다른 계정에서 테스트 할 경우에는 App.jsx에서 accountname 값을 변경해주세요. )
- @donkeeman 님!! 테스트 해보시고 이상하면 말씀 주세욥... !
- 일단 기능만 최대한 동작하도록 만들어서 코드가 난장판일 수 있습니다ㅜㅜ 추후 개선해 나가도록 하겠습니다😥
- 대용량 이미지가 서버에 업로드 되지 않는 이슈가 있어, **이미지를 서버에 업로드전 리사이징** 하는 기능을 추가하였습니다. 
- npm browser-image-compression 패키지 …
> Feat: 상품 등록 페이지 상품 등록 기능 추가 

- src/App.jsx
- src/components/modules/LoginForm/LoginForm.jsx
- src/pages/UploadPage/UploadPage.jsx
- #4 의 로그인 및 인풋 핸들러 함수명을 변경했습니다.
- PR 과정에서 accountname을 사용하는 부분이 겹쳐서 반영이 안 되었는데 다시 수정해 주었습니다.
> Style: 로그인 핸들러 함수명 수정 및 accountname 수정

- src/components/modules/CommentForm/CommentForm.jsx
- src/components/modules/MessageInput/MessageInput.jsx
- src/components/organisms/CommentList/CommentList.jsx
- src/pages/PostPage.jsx
- #9 
댓글 추가 기능을 구현했습니다 테스트 해보세요 
댓글 컴포넌트 UI는 수정중 입니다.
> Feat: 댓글 추가 기능 구현 

- src/global.css
보다보니 스크롤바가 넘 못생겨서..😂스크롤바 custom을 global.css에 추가하였습니다. 모든 스크롤바에 적용됩니다.
> Design: 전체 페이지 스크롤바 custom

- src/components/modules/LoginForm/LoginForm.jsx
- src/components/modules/LoginForm/loginForm.module.css
- src/pages/LoginPage/loginPage.module.css
- #4 , #12 에서 컴포넌트 사이의 간격이 적용이 안 되어 있어서 수정했습니다.
> Design: 로그인, 회원가입 페이지의 컴포넌트 간의 간격 수정

- src/components/atoms/ImageBox/imageBox.module.css
- src/components/atoms/TextArea/textArea.module.css
- src/components/modules/PostCard/PostCard.jsx
- src/components/modules/UploadText/uploadText.module.css
- src/pages/UploadPage/UploadPage.jsx
- src/pages/UploadPage/uploadPage.module.css
- #9 
- #3 
post 할때 다른 처리 없이도 줄바꿈이 \n 으로 전달되기 때문에 
postCard에서 content를 불러올때 \n 기준으로 줄바꿈 하도록 수정하였습니다.
https://coding-hwije.tistory.com/58
> Fix: Post card text 줄바꿈 처리 

- src/components/atoms/PostDate/PostDate.jsx
> Fix: postCard date 컴포넌트에 게시글 업로드 날짜가 나타나도록 변경

- src/pages/AddProductPage/AddProductPage.jsx
- src/pages/AddProductPage/AddProductPageAPI.js
- src/pages/UploadPage/UploadPage.jsx
- src/pages/UploadPage/uploadPage.module.css
> Fix: 리팩토링 하다가 생긴 오류 개선

- src/pages/UploadPage/UploadPage.jsx
- #117
리팩토링하다가 오류가 났었던것 같습니다. 수정하였습니다.!!
> Fix: 이미지 post 갯수 제한 오류 수정

- src/components/atoms/UserNameIntroduce/UserNameIntroduce.jsx
- src/components/atoms/UserNameIntroduce/userNameIntroduce.module.css
- src/components/modules/UserFollow/UserFollow.jsx
- src/components/modules/UserFollow/userFollow.module.css
- src/components/organisms/FollowList/FollowList.jsx
- src/components/organisms/FollowList/followList.module.css
- #13 에서 #121 레이아웃 오류 2가지를 수정하였습니다.
s8
폴드
- 테스트 부탁드립니다!
> Fix: 팔로워/팔로잉 페이지의 레이아웃 오류 수정

- src/common/BASE_URL.jsx
- src/common/ImageUpload.js
- src/components/modules/LoginForm/LoginForm.jsx
- src/components/organisms/ProfileSetting/ProfileSetting.jsx
- src/pages/AddProductPage/AddProductPageAPI.js
- src/pages/FollowerPage.jsx
- src/pages/FollowingPage.jsx
- src/pages/HomePage/HomePage.jsx
- src/pages/PostPage/PostPageAPI.js
- src/pages/ProfileEditPage/ProfileEditPage.jsx
- src/pages/ProfilePage/ProfilePage.jsx
- src/pages/UploadPage/UploadAPI.js
- API에서 사용되는 BASE_URL을 별도 파일로 분리하고 필요한 파일에 import했습니다. #58
- 혹시 안 바뀐 부분이 있으면 제보 부탁드립니다!
> Refactor: BASE_URL 별도 파일로 분리

- src/components/modules/HeaderForm/HeaderForm.jsx
- src/components/modules/LoginForm/LoginForm.jsx
- src/pages/HomePage/HomePage.jsx
- 모달의 로그아웃 버튼을 누르면 로그아웃하는 기능을 추가했습니다. (로컬스토리지에서 토큰, 계정 ID 삭제)
- 로컬스토리지에 토큰이 없을 때 메인 페이지로 가면 로그인 페이지로 이동합니다.
- 로그아웃 후 곧바로 로그인 페이지로 이동해 버리는데, 나중에 splash 페이지가 완성되면 거기로 이동되게 해야겠어요
> Feat: 로그아웃 기능 추가

- src/components/modules/CommentForm/CommentForm.jsx
- src/components/modules/MessageInput/messageInput.module.css
- src/components/organisms/CommentList/CommentList.jsx
- src/global.css
- src/pages/PostPage/PostPage.jsx
- src/pages/PostPage/PostPageAPI.js
- 심화 기능인 댓글 삭제 기능을 추가하였습니다!
- + 추가 ) 하단 입력 폼 사이즈를 조절하였습니다. 또한 global.css padding-bottom 사이즈를 하단 바 및 입력폼 사이즈를 고려해서 48px-> 60px로 수정하였습니다!
> Feat: 댓글 삭제 기능 추가 및 post 페이지 UI 수정 

- src/App.jsx
- #7  App.jsx에 채팅방 경로가 두 번 적혀져 있어서 수정했습니다.
> Fix: 불필요한 코드 삭제

- src/App.jsx
- src/components/atoms/NavItem/navItem.module.css
- src/components/modules/BottomNavigateBar/BottomNavigateBar.jsx
- src/components/modules/CommentForm/CommentForm.jsx
- src/components/modules/HeaderForm/HeaderForm.jsx
- src/components/modules/PostCard/PostCard.jsx
- src/pages/HomePage/HomePage.jsx
- src/pages/SplashPage/SplashPage.jsx
- #164 를 해결하였습니다.
- #2 에서 context로 안 바꿔줬던 부분이 있어서 수정했습니다.
- 하는김에 #2 에서 텍스트 색을 메인 색으로 수정했습니다.
- [페이지가 새로고침되었는지 확인하는 법](https://stackoverflow.com/questions/50026028/react-how-to-detect-page-refresh-f5)
- 페이지가 새로고침되면 setUser를 다시 호출해서 세션 스토리지에서 정보를 받아와서 수정하도록 하였습니다.
- 로그아웃할 때 context를 초기화하는 코드를 추가했습니다.
> Fix: 페이지 새로고침할 때 context 세팅이 안 되던 문제 수정

- src/pages/ErrorPage/ErrorPage.jsx
- src/pages/ErrorPage/errorPage.module.css
- #83 에 메인 페이지로 돌아가는 버튼을 추가했습니다.
- 로고 통일성을 위해 우선 고양이로 바꿔뒀습니다.
> Feat: 404 페이지에 메인 페이지로 가는 버튼 추가

- src/components/modules/PostCard/PostCard.jsx
- src/components/modules/PostCard/PostCardAPI.js
- src/components/modules/Product/Product.jsx
- src/components/modules/Product/product.module.css
- src/components/organisms/ProductList/ProductList.jsx
- src/components/organisms/ProductList/ProductListAPI.js
- src/pages/ProfilePage/ProfilePage.jsx
- #172 를 해결하였습니다.
- [리액트에서 요소가 오버플로우인지 체크하는 법](https://stackoverflow.com/questions/60755083/how-to-check-if-a-div-is-overflowing-in-react-functional-component)
- 말줄임을 하는 대신 상품 이름과 상품 가격에 마우스를 올리면 전체 텍스트를 보여주도록 했습니다.
> Fix: 상품의 가격이 너무 길 경우 말줄임되게 수정

- src/components/modules/Loading/Loading.jsx
- src/components/modules/Loading/loading.module.css
- src/pages/HomePage/HomePage.jsx
- src/pages/PostViewPage/PostViewPage.jsx
- 로딩 컴포넌트를 간단하게 생성해보았습니다...! (디자인은 그냥 기본적이어 보이는걸로 했는데 바꿔도 됩니닷!!)
- 일단 홈 피드와 게시물 상세 보기 페이지에만 적용시켰습니다! 
- 필요하신곳에 써주세요😁
> Feat: Loading 컴포넌트 생성 

- src/pages/FollowerPage/FollowerPage.jsx
- src/pages/FollowingPage/FollowingPage.jsx
- src/pages/ProfilePage/ProfilePage.jsx
- #182 에서 만들어주신 로딩 컴포넌트를 #11, #13 에도 추가했습니다.
> Feat: 프로필 페이지와 팔로워/팔로잉 페이지 로딩 기능 추가

- src/components/atoms/UserInfo/UserInfo.jsx
- src/components/atoms/UserInfo/userInfo.module.css
- src/components/modules/ProfileForm/ProfileForm.jsx
- src/pages/RegisterPage/RegisterPage.jsx
- #180 을 수정하였습니다.
- 소개를 20자 이상 입력하면 에러가 뜨게 설정해줄까 했는데 maxlength를 20으로 줘서 어차피 잘리기 때문에 하지 않았습니다
> Fix: 프로필의 소개 부분에 말줄임표 추가 및 20자로 제한

- src/App.jsx
- src/components/atoms/Chat/UserChat/UserChat.jsx
- src/components/modules/ChatRoom/ChatRoom.jsx
- src/components/modules/ChatRoom/chatroom.module.css
- src/pages/ChatListPage/ChatListPage.jsx
- src/pages/SearchPage/SearchPage.jsx
- 검색 페이지의 중복된 더미데이터를 바꿔주었습니다.
- 채팅목록 유저 프로필 이미지를 추가했습니다. 클릭시 채팅방으로 링크가 연결됩니다.
- 채팅 내용을 진짜 대화처럼 바꿔보았습니다.
- 채팅방에서 상대방의 프로필이미지를 받아올 수 있도록 만들었습니다.
> Fix: 아직 구현되지 않은 기능 더미 데이터 수정 혹은 삽입

- src/common/BASE_IMAGE.jsx
- src/components/modules/ProfileForm/ProfileForm.jsx
- src/components/organisms/ProfileSetting/ProfileSetting.jsx
- src/pages/ProfileEditPage/ProfileEditPage.jsx
- src/pages/ProfileEditPage/ProfileEditPageAPI.js
- src/pages/ProfilePage/ProfilePage.jsx
- src/pages/ProfilePage/ProfilePageAPI.js
- #14 에서 #107 을 해결하였습니다.
- 기본 이미지를 BASE_IMAGE로 분리하여 common 폴더에 넣어주었습니다.
- 회원가입이랑 같은 컴포넌트를 공유하고 있는데 세세하게 역할이 달라서... 잘 작동할지 모르겠습니다. 우선 저는 작동하는데 확인 부탁드립니다!
> Fix: 프로필 수정 시 기존의 데이터를 불러오도록 수정

- src/components/molecules/LoginForm/LoginForm.jsx
> Fix: 로그인 페이지의 버튼 비활성화 오류 수정

- src/common/FollowUser.js
- src/common/UnfollowUser.js
- src/components/molecules/ProfileButton/ProfileButton.jsx
- src/components/molecules/UserFollow/UserFollow.jsx
- src/components/organisms/FollowList/FollowList.jsx
- src/components/organisms/UserProfile/UserProfile.jsx
- src/pages/FollowerPage/FollowerPage.jsx
- src/pages/FollowingPage/FollowingPage.jsx
- src/pages/ProfilePage/ProfilePage.jsx
- #188 을 수정하였습니다.
- 예전에 @boram2445 님께서 사용했던, state를 하나 더 만들어 값이 바뀐 것을 탐지하는 방법을 사용하였습니다... 이게 최선인 것 같습니다
> Fix: 팔로우/언팔로우 시 딜레이가 있던 현상 수정

- README.md
- 리드미  이미지 사이즈나 줄간격 등을 개선하였습니다. 
- 개요에 프로젝트 설명을 추가하였습니다. 
- 등등,, 보기 좋게 개선하였습니다 
- 추후 개선이 필요하면 언제든 수정해주세요😀
> Docs: 리드미 정렬 수정 및 내용 개선

- src/components/atoms/HeaderInput/HeaderInput.jsx
- src/components/molecules/HeaderForm/HeaderForm.jsx
- src/components/molecules/SearchCard/SearchCard.jsx
- src/components/molecules/SearchCard/searchCard.module.css
- src/pages/SearchPage/SearchPage.jsx
- src/pages/SearchPage/SearchPageAPI.js
- src/pages/SearchPage/searchPage.module.css
- #203 
- 검색 기능을 추가하였습니다. 
- 검색한 키워드에 색상이 넣어지도록 하였습니다
- 테스트 해보시고 오류가 있으면 말씀해 주세요!!
- useCallback을 이용해서 최적화 노력을 하긴 했는데, 원범님이 말씀하신게 이 최적화 맞는지는 모르겠네요 나름 빠른것 같긴 합니당😚
> Feat: Search page 검색기능 추가 

- src/App.jsx
- #145 를 App.jsx에서 토큰을 받아올 때 해줬어야 하는데 깜빡해서 수정했습니다. 
- 로그인할 때 검증하지 말고 App.jsx에서만 검증해도 될 거 같기도 합니다.
> Fix: App.jsx에서 토큰 유효성 검사하도록 수정

- README.md
- 리드미에 배포 링크를 추가하였습니다.
- 제 역할 추가했습니다 😅😅
- 깨져 보이는 이미지를 수정하였습니다.
- [firebase로 배포하기](https://velog.io/@cyongchoi/React-%EB%A5%BC-Firebase-%EB%A1%9C-%EB%B0%B0%ED%8F%AC%ED%95%98%EA%B8%B0)
- [firebase url 바꾸기](https://romeoh.tistory.com/70)
- @yeodahui 님! 좋아요 구현을 제가 해버려서 부득이하게 다희님 역할에는 ui라고만 적어두었습니다... 그러니까 내용이 빈약해진 거 같아서 더 적어보려고 했는데, 저는 다른 분들 역할 잘 모르니까 다희님 파트는 시간나실 때 더 적어주세요!
> Docs: README.md 파일에 배포 링크 추가 및 내용 수정

- src/common/BASE_URL.jsx
> Fix: 변경된 URL으로 수정
