public/index.html, src/app.css, src/components/organisms/LoginPageForm/LoginPageForm.jsx, src/reset.css
reset.css 파일을 public 폴더에서 src 폴더로 옮기고, reset 관련이 아닌 전역적으로 적용할 스타일을 app.css로 분리하였습니다.
=> Fix: reset.css가 하위 페이지에서 적용되지 않던 오류 수정

src/components/atoms/ImageBox/imageBox.module.css, src/components/modules/UserFollow/UserFollow.jsx, src/components/modules/UserFollow/userFollow.module.css
- #13 에서 필요한 유저 사진과 정보, 팔로우 버튼이 결합된 모듈을 만들었습니다.
https://stackoverflow.com/questions/50746912/how-to-style-child-components-in-react-with-css-modules
- 피그마를 그대로 따라해서 우선은 width가 고정값입니다.
- css 이슈는 레퍼런스 링크의 방법대로 우선 해결했지만, 더 나은 방법이 있는지 찾아보겠습니다!
- 이미지가 찌그러지는 문제가 있어서 임시방편으로 ImageBox의 circle 부분만 css를 max-width, min-height로 수정했습니다. (이미지 적용 전에 불러올 때 미리 잘라주는 방법을 사용해야 할 지도 모르겠습니다.)
- 테스트용으로 useState를 이용해서 버튼을 클릭할 때마다 팔로우/취소 로 바뀌도록 했습니다.
=> Feat: 팔로우/팔로잉 유저 정보를 보여주는 UserFollow 컴포넌트 및 css 구현

src/components/atoms/NumberFollow/NumberFollow.jsx, src/components/atoms/NumberFollow/numberFollow.module.css
- #11 에서 보여질 팔로워/팔로잉 수를 나타내는 컴포넌트를 구현했습니다.
- 이 컴포넌트는 링크라서 누르면 팔로워/팔로잉 페이지로 이동합니다.
- 원래 url에는 :accountname이 들어가는데, 아직 api까지 테스트하진 않아서 우선 빼놓았습니다.
=> Feat: 팔로워/팔로잉 수를 나타내는 컴포넌트 및 css 구현

src/components/atoms/ImageBox/imageBox.module.css, src/components/modules/UserProfileBox/UserProfileBox.jsx, src/components/modules/UserProfileBox/userProfileBox.module.css
- #11 의
부분을 구현했습니다.
- 드디어 이미지가 안 찌그러지도록 css 수정을 마친 것 같은데, 추후에 댓글 등 다른 곳에서 테스트 부탁드립니다!
- 커밋하고 알았는데 이미지에 alt값을 안 넣었어요. 나중에 꼭 넣겠습니다!
=> Feat: 유저 정보, 팔로워/팔로잉 수, 프로필 사진을 결합한 컴포넌트 및 css 구현

src/assets/icon-message-circle.svg, src/assets/icon-share.svg, src/components/atoms/IconButton/IconButton.jsx, src/components/atoms/IconButton/IconButton.module.css, src/components/modules/MyProfileButton/MyProfileButton.jsx, src/components/modules/MyProfileButton/myProfileButton.module.css, src/components/modules/ProfileButton/ProfileButton.jsx, src/components/modules/ProfileButton/profileButton.module.css
- #11 에서
부분을 구현했습니다.
- 나의 프로필 페이지에서는 MyProfileButton 컴포넌트가, 타인의 프로필 페이지에서는 ProfileButton 컴포넌트가 보이게 됩니다.
=> Feat: 유저 프로필 하단의 버튼이 결합된 컴포넌트 구현

src/App.jsx, src/assets/icon-message-circle.svg, src/assets/icon-share.svg, src/components/atoms/IconButton/IconButton.jsx, src/components/atoms/IconButton/IconButton.module.css, src/components/atoms/ImageBox/imageBox.module.css, src/components/atoms/NumberFollow/NumberFollow.jsx, src/components/atoms/NumberFollow/numberFollow.module.css, src/components/modules/MyProfileButton/MyProfileButton.jsx, src/components/modules/MyProfileButton/myProfileButton.module.css, src/components/modules/ProfileButton/ProfileButton.jsx, src/components/modules/ProfileButton/profileButton.module.css, src/components/modules/UserProfileBox/UserProfileBox.jsx, src/components/modules/UserProfileBox/userProfileBox.module.css, src/components/organisms/UserProfile/UserProfile.jsx, src/pages/ProfilePage.jsx
- #11 에서 프로필 부분을 올가니즘화하고, /profile 페이지를 생성했습니다.
- (다 머지하고 나서) /profile 들어가시면 헤더와 결합한 임시 프로필 페이지가 나옵니다. 밑에 판매중인 상품 목록과 게시글 목록을 추가하면 페이지 완성... 😂
=> Feat: 사용자 프로필 컴포넌트, css 구현 및 페이지 생성

src/components/modules/Product/Product.jsx, src/components/modules/Product/product.module.css
- #11 의 판매 중인 상품 목록 부분에 들어갈 상품 컴포넌트를 구현했습니다.
- 상품 제목이 길어지면 말줄임표로 생략되게 하였습니다.
- 가격은 `toLocaleString("en-US")` 함수를 이용하여 `,`로 분리되게 하였습니다.
=> Feat: 판매 중인 상품 목록에 들어갈 상품 컴포넌트 및 css 구현

src/components/organisms/ProductList/ProductList.jsx, src/components/organisms/ProductList/productList.module.css
- #11 에서 사용자 프로필 밑에 있는 **판매중인 상품** 부분의 리스트를 컴포넌트화했습니다.
- 상품의 수가 많아지면 x축만 자동으로 스크롤이 생기도록 했습니다. (`overflow-x: auto;`)
=> 판매 중인 상품 리스트 컴포넌트 및 css 구현

src/App.jsx, src/assets/x.svg, src/components/atoms/IconButton/iconButton.module.css, src/components/atoms/ImageBox/imageBox.module.css, src/components/atoms/ImageInputButton/ImageInputButton.jsx, src/components/modules/ImageInputForm/ImageInputForm.jsx, src/components/modules/PostImage/PostImage.jsx, src/components/modules/PostImage/postImage.module.css, src/components/organisms/PostForm/PostForm.jsx, src/components/organisms/PostForm/postForm.module.css, src/pages/UploadPage/UploadPage.jsx, src/pages/UploadPage/uploadPage.module.css
- #10 
UI 작업을 완료하였습니다. 
1) 상품 이미지가 하나일때 - 큰 이미지
2) 상품 이미지가 여러개일때 - 리스트로 정렬
- 이미지 추가 버튼, 이미지 삭제 버튼 기능도 작동합니다😆
- /post 로 이동하셔서 확인해보시고 이상한 부분 지적해주세요!
- 텍스트 길이 제한, 이미지 추가 개수 제한은 이후 추가해야할 사항입니다!
=> Feat: 상품 업로드 페이지 UI 완성

src/components/modules/MessageInput/MessageInput.jsx, src/components/modules/MessageInput/messageInput.module.css
- #9 
1) 입력전 - 버튼 비활성화
2) 입력 후 - 버튼 활성화 
```
<MessageInput
type="comment"
src=""
title="댓글"
placeholder="댓글 입력하기..."
buttonText="게시"
/>
```
- #7 
```
<MessageInput
type="message"
title="메세지"
placeholder="메세지 입력하기..."
buttonText="전송"
/>
```
- @hee1231 님!! 채팅 페이지에서도 텍스트 입력 하단 컴포넌트가 필요한 것 같아 같이 만들었습니다! 활용해주세요 :>
- 텍스트를 입력하면, 버튼이 활성화 됩니다. 
- 컴포넌트가 보여질때 바로 input에 focus됩니다.
=> Feat: 포스트 페이지, 채팅 페이지 하단 댓글, 채팅 입력 모듈 컴포넌트 UI 생성

src/App.jsx, src/components/atoms/NumberFollow/NumberFollow.jsx, src/components/modules/HeaderForm/headerForm.module.css, src/components/modules/Product/Product.jsx, src/components/modules/UserFollow/UserFollow.jsx, src/components/modules/UserFollow/userFollow.module.css, src/components/organisms/FollowList/FollowList.jsx, src/components/organisms/FollowList/followList.module.css, src/components/organisms/ProductList/ProductList.jsx, src/components/organisms/ProductList/productList.module.css, src/pages/FollowerPage.jsx, src/pages/FollowingPage.jsx, src/pages/ProfilePage.jsx
- #13 의 마크업을 완료했습니다. (팔로우/취소 기능 구현은 아직입니다..)
- #11 의 판매중인 상품 목록을 사용자가 판매하는 목록으로 가져왔습니다.
- 상품 목록과 팔로워/팔로잉 목록이 비어 있으면 비어 있다는 메시지를 출력하게 했습니다.
- 상품 컴포넌트에 링크를 달아주긴 했는데, 상품 게시글은 상세 페이지가 따로 없어서 사람들이 링크를 유튜브나 네이버 같은 걸로 적어 놓았더라고요. 아예 링크를 뺄까 생각중입니다.
- 팔로워/팔로잉 페이지의 이미지나 이름을 누르면 그 사람의 페이지로 이동하게 했습니다.
- 팔로워/팔로잉 목록이 로딩 중일 때, 비어 있을 때 나오는 메시지가 출력됐다가 사라집니다. 로딩 중인 상태를 체크하는 기능을 추가하겠습니다.
- 팔로우/취소 기능은 아직입니다. 빨리 구현하겠습니다. 😅
=> Feat: 팔로워/팔로잉 페이지 구현

src/App.jsx, src/components/atoms/TextArea/TextArea.jsx, src/components/modules/UploadText/UploadText.jsx, src/components/organisms/UploadForm/UploadForm.jsx, src/pages/UploadPage/UploadPage.jsx
- #10 
텍스트와 이미지 업로드 기능을 구현하였습니다. 
- 글 입력시 업로드 버튼 활성화 구현
- 버튼 클릭시 게시글 업로드 구현
- 업로드 버튼을 누르면 /profile/${accoutname} 으로 이동합니다. 
1) 텍스트 미 입력 - 업로드 버튼 비활성화
2) 텍스트, 이미지 모두 입력 - 업로드 버튼 활성화
3) post가 성공적으로 되었는지 확인
- 이미지를 변경할때마다 서버에서 url을 받아와 보여주니 동작이 느려서, 
업로드 버튼을 클릭하면 이미지 url을 받아오고, 데이터를 전송하도록 변경했습니다. 
(상품업로드 페이지에서도 이처럼 수정하려고 합니다)
- 여러 이미지 업로드 api를 이용하여, 한꺼번에 여러 image file를 서버에 보냈더니 가끔 다른 image file이 같은 url을 갖고 돌아오는 오류가 있어 이미지를 하나씩 서버로 보내도록 하여 해결했습니다. (추후 멘토님께 여쭤보도록 하겠습니다..!)
- 프로필 이미지는 로그인 구현 후 app.jsx에서 profile데이터를 받아와 처리해야 할 것 같습니다.
=> Feat: Upload page 텍스트, 이미지 업로드 기능 구현

src/App.jsx, src/components/atoms/InputBox/InputBox.jsx, src/components/modules/LoginForm/LoginForm.jsx, src/components/organisms/UserProfile/UserProfile.jsx, src/pages/AddProductPage.jsx, src/pages/ProfilePage.jsx
- #4 의 로그인 및 유효성 검사 기능 구현을 완료했습니다.
- 로그인한 계정의 accountname을 로컬 스토리지에 저장하여 accountname이 필요했던 페이지에서 받아오게 하였습니다.
- useContext의 지속성: https://stackoverflow.com/questions/68548627/react-context-value-disappears-when-reloading-page
- useRef를 커스텀 컴포넌트에서 사용하는 법: https://stackoverflow.com/questions/56484686/how-do-i-avoid-function-components-cannot-be-given-refs-when-using-react-route
- 로그인 버튼이 클릭되었을 때, 경우에 따라 에러 처리를 했습니다. 그리고 에러인 부분의 input에 포커스를 주었습니다. (이미지는 포커스되게 수정하기 전에 찍었어요..)
- 로그인이 정상적으로 되면 루트 페이지로 이동하도록 하였습니다.
- 기존 isMe로 내 계정인지 아닌지 대충 판별했었는데 accountname으로 제대로 판별되게 하였습니다.
- 상품 등록 페이지에서 저장을 누르면 저장된 accountname의 프로필 페이지로 가도록 했습니다.
=> Feat: 로그인 기능 구현 및 accountname으로 로그인한 계정 판별

src/App.jsx, src/pages/AddProductPage.jsx, src/pages/UploadPage/UploadPage.jsx
- #8 
Add Product 페이지에서 상품 등록 페이지의 이미지 프리뷰 기능을 이미지 변경시마다 서버에서 url을 받아오는 것이 아니라, URL.createObjectURL을 사용하도록 하여 빠르게 이미지가 변경될 수 있도록 하였습니다.
=> Fix: Add product 페이지 이미지 프리뷰 개선

src/pages/FollowerPage.jsx, src/pages/FollowingPage.jsx
- #13 의 팔로워/팔로잉 목록에서 한 번 불러올 때 최대 10명까지밖에 안 되는 제한이 있었는데, `limit=Infinity` 쿼리를 이용해서 전체 팔로워/팔로잉 목록을 불러오도록 수정했습니다.
- limit에 한 번에 불러올 수 있는 최대 개수를 지정해줄 수 있는데, 전체를 불러오고 싶었는데 fetch 과정에서 현재 팔로잉/팔로워 수를 불러오려면 다른 fetch를 한번 더 써야 하더라고요.
그래서 우선은 제한이 없는 `Infinity`로 지정해 주었습니다. 원범님께 여쭤 보고 더 효율적인 코드가 있다면 그걸로 바꿔볼게요!
=> Fix: 팔로워/팔로잉 목록에서 불러오는 인원 수의 제한 해제

src/components/modules/PostCard/PostCard.jsx, src/pages/HomePage/HomePage.jsx
#75
홈피드에 게시글 데이터를 불러올 때, image 프로퍼티에 여러 개의 이미지의 경우 `"{url}, {url}, ..."` 와 같이 문자열 형식으로 가져와 이미지가 정상 출력되지 않는 문제가 있었습니다.
- HomePage.jsx에서 게시글 데이터 불러올 때 각 포스트의 image 프로퍼티의 정보를 배열로 변경
- PostCard.jsx에서 props로 받은 이미지 URL 배열 요소 개수만큼 이미지를 출력하게 수정
결과입니다. 
이미지 url의 개수대로 이미지 컴포넌트가 생성되었으나, **교차 출처 읽기 차단(CORB)으로 인해** 소스를 제대로 가져오지 못하는 문제가 있어 이슈로 등록하였습니다. #76 
==========
**이미지 주소를 잘못 전달하고 있어 수정했습니다! 정상적으로 이미지가 나옵니다.**
=> Fix: 게시글에 이미지가 개수만큼 출력되게 수정

src/pages/HomePage/HomePage.jsx, src/pages/UploadPage/UploadPage.jsx
이미지 url 여러개를 서버에 보낼 경우 ', '(콤마+공백) 에서 ',' (콤마)로만 구분하도록 변경하였습니다 :)
=> Fix: 이미지 url을 콤마로만 구분하도록 변경

src/App.jsx, src/components/atoms/IconButton/iconButton.module.css, src/components/modules/CommentForm/CommentForm.jsx, src/components/modules/CommentForm/commentForm.module.css, src/components/modules/HeaderForm/HeaderForm.jsx, src/components/modules/InfoIconGroup/InfoIconGroup.jsx, src/components/modules/MessageInput/messageInput.module.css, src/components/modules/PostCard/PostCard.jsx, src/components/modules/PostCard/postCard.module.css, src/components/organisms/CommentList/CommentList.jsx, src/components/organisms/CommentList/commentList.module.css, src/pages/HomePage/HomePage.jsx, src/pages/PostPage.jsx
- #9 
- 피드에서 댓글 아이콘을 클릭하면 /post/:postId 경로로 이동합니다. 
- 해당 피드의 postId를 받아와 피드 상세 정보와 댓글 리스트를 불러옵니다. 
- 댓글이 몇일전 작성한 것인지 나타내 주는 기능도 추가하였습니다. 
- 헤더 컴포넌트에서 계속 발생하는 onClick 오류를 해결하였습니다.
- @yeodahui 님!!  Post 상세 보기 페이지에서도, 이미지 url split 가 필요해서, 해당 기능을 HomePage -> PostCard 컴포넌트로 이동하였습니다!! 어떤 부분을 수정했는지 보여드려야 할 것같아 HomePage.jsx에서 해당 부분은 주석처리 해놓았습니다!!
- useEffect에서 데이터를 불러오는 것이 페이지 render보다 오래걸려서 계속 데이터가 페이지에 undefined로 나타난 이슈가 있었습니다.. 하루종일 뻘짓 했습니다ㅠㅠ 흑흑 
혹시나 이런 경험 하실까봐 공유해드려요 [참고 스택오버플로우](https://stackoverflow.com/questions/65687852/fetch-data-inside-useeffect-hook-before-rendering-react)
=> 결론 (데이터가 있을때만 해당 컴포넌트가 보여지게 조건문을 달아라^^
```
{post && <PostCard post={post} />}
{comments && <CommentList comments={comments} />}
```
=> Feat: Post 상세보기 페이지 post 데이터 및 댓글 데이터 불러오기 기능 추가 

src/components/modules/HeaderForm/headerForm.module.css, src/global.css
- 내용이 많아져 스크롤 할떄 헤더가 상단에 고정되도록 하였습니다. 
- **로그인, 이메일로 회원가입 페이지**를 제외하고는 모두 헤더가 있어서, **global.css**에서 body에 padding-top을 부여하였습니다.
로그인 페이지에서 padding-top이 추가로 부여되어 컨텐츠가 아래로 조금 내려간 모습입니다. 
사실 이게 중앙에 배치되어 더 예뻐보이긴 하는데,, 피그마 대로 해야한다고 하면 어떻게 효율적으로 수정할지 고민해보겠습니다ㅎㅎㅎ😂 의견남겨주세요
=> Design: Header 컴포넌트를 fixed로 고정 

src/App.jsx, src/pages/ChatListPage/ChatListPage.jsx, src/pages/ChatListPage/chatListPage.module.css
#6 채팅 목록 페이지 마크업을 구현하였습니다. 더미 데이터를 이용해 API와 연동 시 데이터를 쉽게 넣을 수 있도록 만들었습니다.
- 채팅 목록 페이지 생성 및 라우트에 연결(/chat)
- 읽지 않은 채팅 표시
- 채팅목록에서 메시지가 길 때 말줄임
메세지 블럭과 날짜 블럭을 나란히 둬야 해서 부모 요소에 flex 태그를 주었더니, 말줄임이 안되더라고요.
flex 박스는 flex-wrap이 nowrap일 경우 콘텐츠 너비 이상으로 박스가 줄어들지 않기 때문이었습니다.
flex 대신 grid를 사용했더니 정상적으로 적용되었습니다.
=> Feat: 채팅목록 페이지 마크업 구현

src/components/atoms/ImageBox/imageBox.module.css
imageBox에서 
```
.image img {
height: 100%;
width: 100%;
object-fit: cover;
}
```
했더니 작은 이미지가 깨지네요 따이쉬..
기본 설정을 원래대로 돌려주고 게시글에서만 적용되도록 해주었습니다. 
```
.rounded_square.medium_large img {
height: 100%;
width: 100%;
}
```
=> Fix: ImageBox 작은 이미지 깨짐 현상 수정

src/components/atoms/ImageBox/imageBox.module.css, src/components/atoms/TextArea/textArea.module.css, src/components/modules/UploadText/uploadText.module.css, src/pages/UploadPage/UploadPage.jsx, src/pages/UploadPage/uploadPage.module.css
- #10 
- 텍스트 입력이 **화면 height의 60퍼센트**를 넘어가면 스크롤되도록 하였습니다. 
- flex를 사용했더니 프로필 이미지 박스가 찌그러져 **grid로 변경**하였습니다. 
- #61   
- ImageBox 컴포넌트에서 모든 .rounded_square img 에만 height: 100%;
width: 100% 이 적용하여 이미지가 박스에 꽉차도록 해주었습니다. 
(circle의 경우 위와 같이 적용하니 작은 박스에서 이미지가 깨지는 현상이 있어 max-height max-width로 남겨놨습니다)
=> Desing: Upload 페이지 UI 개선

src/components/modules/LoginForm/LoginForm.jsx, src/components/modules/ProfileForm/ProfileForm.jsx, src/components/organisms/ProfileSetting/ProfileSetting.jsx
- #4, #12 의 너무 많았던 state 개수를 줄이고, 함수명을 직관적으로 변경했습니다.
- https://jeonghwan-kim.github.io/dev/2022/03/29/react-form-and-formik.html
- value와 error 두 개의 state를 선언하고 기존 state들을 객체화해서 합쳤습니다.
- 값을 가져올 땐 `value.email` 처럼 접근합니다.
- 값을 설정할 땐 `setValue({...value, email: "..."})` 식으로 전개 구문을 통해 부분 업데이트가 가능합니다.
- 기능은 제대로 작동하는 거 같은데 혹시 에러나는 부분이 있다면 이슈 등록해 주세요!
=> Refactor: 로그인, 회원가입의 state 통합 및 함수명 직관적으로 변경

src/components/atoms/Comment/Comment.jsx, src/components/atoms/PostDate/PostDate.jsx, src/components/modules/PostCard/PostCard.jsx
post의 작성자 이미지 src 정보가 post데이터 받아오면서 함께 가져와지길래 배치했습니당! (초록부분)
아래 현재 계정 이미지(파란부분)는 아직 어디에서 받아와야 하는지 모르겠습니다!!ㅎ_ㅎ
=> Design: PostCard 게시물 작성 유저 이미지 추가

src/components/modules/MyProfileButton/myProfileButton.module.css, src/components/modules/UserProfileBox/userProfileBox.module.css, src/components/organisms/ProductList/ProductList.jsx, src/components/organisms/UserProfile/UserProfile.jsx, src/components/organisms/UserProfile/userProfile.module.css
- #11 에서 화면 너비가 좁아졌을 때 버튼이 줄어드는 이슈 #91 을 수정하였습니다.
- #11 에서 프로필 컴포넌트와 판매중인 상품 컴포넌트의 태그를 `<div>` 대신 `<section>`으로 변경하였습니다.
-  기존 제 화면에선 차이가 없어서 잘 몰랐는데 좌우 마진을 고정값으로 줘서 생겼던 문제 같습니다. @yeodahui 님 테스트 부탁드려요!
=> Design: 프로필 페이지의 버튼 css 수정 및 마크업 수정

src/components/modules/ProfileButton/ProfileButton.jsx, src/components/modules/ProfileButton/profileButton.module.css
- #11 에서 타인의 프로필 페이지의 팔로우 버튼을 누르면 언팔로우로, 다시 누르면 팔로우로 바뀌게끔 했습니다.
- 실제 팔로우 기능은 도전과제라 아직 구현하지 않았습니다.
- gif 찍는 프로그램이 없어서 못 보여드리는데, 버튼이 팔로우->언팔로우, 언팔로우->팔로우 로 바뀌면서 밑에 있는 판매중인 상품 컴포넌트가 살짝씩 위아래로 움직입니다? 왜이러는지 원인을 모르겠어요 추후에 확인 부탁드립니다..
=> Feat: 팔로우 버튼을 클릭하면 팔로우/언팔로우로 바뀌도록 구현

src/components/atoms/Author/Author.jsx, src/components/modules/PostCard/PostCard.jsx
게시글 컴포넌트에서 유저 프로필 사진 영역을 클릭하면 이동이 없었고, 닉네임, 아이디를 클릭하면 `/profile/:accountname`이 아닌 `/:accountname`으로 이동되었던 것을 올바른 경로로 이동하게 만들었습니다.
=> Fix: 게시글에서 유저 영역 클릭 시 이동하는 링크 수정

src/pages/UploadPage/UploadAPI.js, src/pages/UploadPage/UploadPage.jsx
- #10 에서 이미지가 있어야 활성화되던 업로드 버튼을 이미지 없이 텍스트만 있어도 활성화되도록 변경했습니다.
=> Fix: 게시글 업로드 시 이미지가 없어도 버튼 활성화되게 수정

src/components/atoms/NavItem/NavItem.jsx, src/components/atoms/NavItem/navItem.module.css, src/components/modules/BottomNavigateBar/BottomNavigateBar.jsx, src/components/modules/BottomNavigateBar/bottomNavigateBar.module.css, src/pages/ChatListPage/ChatListPage.jsx, src/pages/FollowerPage.jsx, src/pages/FollowingPage.jsx, src/pages/HomePage/HomePage.jsx, src/pages/ProfilePage.jsx, src/pages/SearchPage/SearchPage.jsx
#2 하단바를 추가하였습니다.
- 하단 네비게이션 바 컴포넌트
- 네비게이션 아이템 컴포넌트
현재 페이지에 따라 하이라이트 되는 기능이 미완성입니다.
contextAPI를 통해 accountname과 현재 페이지를 추적하려고 하는데, 메인 브랜치에 push된 코드들을 꺼내오고싶어 중간 PR 날립니다!
=> Feat: 하단 탭 메뉴 구현

src/common/ImageUpload.js, src/pages/UploadPage/UploadAPI.js, src/pages/UploadPage/UploadPage.jsx
- 여러 이미지 업로드와 한개 이미지 업로드 API 코드 중복되는 부분이 많아서 하나로 합쳤습니다. 
- 여러 이미지 업로드를 할 경우에도 filename이 아닌 url을 리턴하도록 하여 코드를 줄였습니다.
=> Refactor: 이미지 업로드 함수 중복 코드 제거

src/components/modules/BottomNavigateBar/BottomNavigateBar.jsx
#2 하단 탭에서 프로필을 클릭할 경우 jordi3 유저의 프로필 페이지로만 이동하던 것을, 로컬 스토리지에 저장된 accountname을 불러와 이동하도록 만들었습니다.
=> Fix: 하단바 프로필 클릭 시 로컬에 저장된 accountname의 프로필로 이동

src/components/modules/Product/Product.jsx, src/components/organisms/ProductList/ProductList.jsx, src/components/organisms/ProductList/productList.module.css, src/components/organisms/UserProfile/UserProfile.jsx, src/pages/ProfilePage/ProfilePage.jsx
- #11 에서 내 프로필 페이지일 경우, 판매중인 상품 목록에서 상품을 누르면 모달이 뜨도록 하였습니다. 웹사이트에서 상품 보기를 누르면 상품의 링크로 이동합니다.
- 내 프로필 페이지가 아니라면 바로 상품의 링크로 이동합니다.
- [리액트로 외부 링크 띄우기](https://jaimemin.tistory.com/1449)
- 모달 삭제, 수정 `onclick` 부분에 `() => {}` 로 해놨는데... 괜찮을까요?
- 다른 내용이지만 내 프로필인지 검사하는 걸 useState 이용하고 fetch보다 위에 두었더니 버튼 로딩이 좀 짧아진 거 같아요?
=> Feat: 나의 프로필 페이지에서 상품 누르면 모달 뜨는 기능 추가

src/components/atoms/NavItem/NavItem.jsx, src/components/modules/BottomNavigateBar/BottomNavigateBar.jsx, src/contexts/curruntPageContext.jsx
#2 ContextAPI를 사용해 현재 탭에 하이라이트를 주려고 합니다.
하지만 하단바 중 프로필 탭만 하이라이트 되고 다른 컴포넌트들은 클릭해 위치가 이동되더라도 컬러가 바뀌지 않습니다.
- 혹시 오류가 있어 보이는 부분이 있다면 알려주세요!
- 이걸 ContextAPI를 사용해서 처리하는 게 맞을까요...?
- 차라리 `window.location.pathname`를 받아와서 path에 따라 변경되게 하거나
- 페이지 컴포넌트에서 BottomNavigationBar컴포넌트에 props를 전달하는 편이 좋을까요?
=> Feat: ContextAPI 사용하여 현재 탭에 하이라이팅

src/components/atoms/InputBox/InputBox.jsx, src/components/modules/LoginForm/LoginForm.jsx, src/components/modules/ProfileForm/ProfileForm.jsx, src/components/organisms/ProfileSetting/ProfileSetting.jsx, src/pages/ProfileEditPage/ProfileEditPage.jsx
- #4, #12, #14 에서 버튼 클릭 대신 엔터를 눌러도 함수가 실행되게 하였습니다.
- 판매 상품 게시, 게시글 작성 부분 등은 글을 쓸 때 엔터를 쓰기 때문에 안 넣었습니다!
- 회원가입, 프로필 수정 같은 경우는 소개 부분이 맨 마지막 input이라 거기에 이벤트를 넣긴 했는데, 소개 부분이 필수가 아니다보니 계정 ID에 이벤트를 주어야 할지 고민입니다. 어떻게 생각하세요?
=> Feat: 로그인/회원가입/프로필 수정을 엔터로도 실행되게 하는 기능 추가

src/components/atoms/ImageBox/imageBox.module.css, src/components/organisms/FollowList/FollowList.jsx, src/components/organisms/FollowList/followList.module.css, src/pages/ProfileEditPage/ProfileEditPage.jsx, src/pages/ProfileEditPage/profileEditPage.module.css, src/pages/SplashPage/splashPage.module.css
- wrapper-content 추가 후 #1, #13, #14 의 패딩을 재조절해 주었습니다.
#146, #148
- ImageBox 컴포넌트의 width, height 값을 모두 100%로 변경했습니다. 
#149
- #13 에서 팔로워/팔로잉이 없을 때 뜨는 창에서 이모지 대신 로고로 변경했습니다.
- 이미지 제대로 출력되는지 확인 부탁드립니다!
=> Design: 패딩 삭제 후의 패딩값 변경 및 이미지 비율 조절

src/components/atoms/NavItem/NavItem.jsx, src/components/atoms/NavItem/navItem.module.css, src/components/modules/BottomNavigateBar/bottomNavigateBar.module.css
#147 화면이 좁아질 경우 하단탭의 height가 높아져 페이지 하단 내용을 가리는 현상을 해결했습니다.
4개의 모든 아이콘이 같은 너비를 가지게 하려면 flex보다 grid가 적용이 쉬워 기존의 flex 레이아웃을 grid로 변경했습니다.
하지만 grid로 작업했을 때에도 너비가 계속 작아지면 글씨 영역이 깨질 수 밖에 없는데, 그럴 일은 잘 없겠지만 화면너비가 300px 이하일 때는 아이콘 이름이 사라지게 만들었습니다.
=> Fix: 화면이 좁아질 때 하단 탭 "게시글 추가"가 줄바꿈이 일어나는 현상 해결

src/pages/ProfilePage/ProfilePage.jsx, src/pages/ProfilePage/profilePage.module.css
- #11 의 게시글 목록에서 앨범형으로 볼 때의 css를 grid와 미디어 쿼리를 이용하여 수정했습니다.
#144 
- image가 있는지 없는지를 li 안에 넣어 돌리고 있었습니다... 그래서 이미지가 없어도 li가 생기고 간격이 이상해졌었나 봐요...
=> Fix: 프로필 페이지의 게시글 앨범형으로 볼 때의 css 반응형으로 수정

src/components/modules/CommentForm/CommentForm.jsx, src/components/modules/ModalRequestion/ModalRequestion.jsx, src/components/modules/PostCard/PostCard.jsx, src/components/modules/PostCard/PostCardAPI.js, src/components/organisms/CommentList/CommentList.jsx, src/components/organisms/Modal/Modal.jsx, src/pages/PostPage/PostPage.jsx, src/pages/PostPage/PostPageAPI.js
- #153 
- 모달에서 신고하기 버튼 클릭시 재확인 버튼이 뜨도록 수정하였습니다. 
- 다른 사람의 게시글과 댓글에 신고하기 기능을 추가하였습니다. 
- 딱히 신고를 한다음에 UI에 변화는 없어서 api보내고 응답 받는것으로 잘 되는지 테스트를 해보았습니당!
=> Feat: 게시물 및 댓글 신고 기능 추가 

src/pages/SplashPage/splashPage.module.css
- #1 
- 스플래시 화면이 app.jsx에 적용된 max-width로 인해 좌우 여백이 남는것을 개선해 보았습니다!
- 배경색 주석처리해놓으신것 보니까 혜원님도 같은 고민 하셨던것 같아요!!🙌 
전체화면으로 고치니까 별도 많아지고 더 예쁜것 같아 변경해보았습니다 
(전체화면의 경우)
=> Design: 스플래시 화면 꽉채우기

src/App.jsx, src/common/ImageUpload.js, src/components/modules/BottomNavigateBar/BottomNavigateBar.jsx, src/components/modules/HeaderForm/HeaderForm.jsx, src/components/modules/LoginForm/LoginForm.jsx, src/components/modules/UploadText/UploadText.jsx, src/contexts/LoginedUserContext.jsx, src/pages/AddProductPage/AddProductPage.jsx, src/pages/AddProductPage/AddProductPageAPI.js, src/pages/FollowerPage/FollowerPage.jsx, src/pages/FollowerPage/FollowerPageAPI.js, src/pages/FollowingPage/FollowingPage.jsx, src/pages/FollowingPage/FollowingPageAPI.js, src/pages/HomePage/HomePage.jsx, src/pages/PostEditPage/PostEditPage.jsx, src/pages/PostEditPage/PostEditPageAPI.js, src/pages/PostPage/PostPage.jsx, src/pages/PostPage/PostPageAPI.js, src/pages/ProfileEditPage/ProfileEditPage.jsx, src/pages/ProfileEditPage/ProfileEditPageAPI.js, src/pages/ProfilePage/ProfilePage.jsx, src/pages/ProfilePage/ProfilePageAPI.js, src/pages/SearchPage/SearchPage.jsx, src/pages/SplashPage/SplashPage.jsx, src/pages/UploadPage/UploadAPI.js, src/pages/UploadPage/UploadPage.jsx
- 로컬스토리지에 저장했던 토큰 등을 세션스토리지에 저장하게 수정하였습니다.
- 세션스토리지에 저장한 프로필 이미지를 필요한 곳에 적용하였습니다.
**- (추가!) 세션 스토리지의 정보를 매번 불러오는 것이 아니라 useContext를 이용하여 관리하게 수정했습니다.**
- 토큰이 없을 때: 로그인할 때 세션 스토리지에 정보를 저장하고, 동시에 세션 스토리지에서 정보를 받아와서 context에 세팅합니다. (로그인하면 바로 피드 페이지로 이동하기 때문에)
- 토큰이 있을 때: 스플래시와 App.jsx에서 세션 스토리지에서 정보를 받아와서 context에 세팅합니다.
App.jsx에서 하고는 있지만, 스플래시가 초기 화면이라 안전장치로 스플래시도 해줬는데 스플래시에서 빼도 정상작동하는 걸 확인하면 스플래시는 뺄게요! 
- 로그아웃하면 세션 스토리지를 초기화합니다.
- 그 외의 페이지에선 context에서 토큰, 계정 ID, 프로필 이미지를 받아와서 사용합니다.
매번 세션 스토리지에 접근하는 것보다 낫지 않을까 해서 한 건데 성능 향상에 효과가 있을지는 모르겠습니다 😅 
- @boram2445 님께서 말씀해 주셨던 로그아웃하고 나서 다시 로그인해서 댓글쓸때 이전 계정으로 쓰이는 문제는 저는 해결된 거 같은데 테스트 부탁드립니다!
=> Fix: 로컬스토리지 대신 세션스토리지에 계정 정보 저장 및 프로필 사진 뜨도록 수정

src/pages/ProfileEditPage/ProfileEditPage.jsx, src/pages/ProfileEditPage/ProfileEditPageAPI.js
- #11 에서 프로필 수정한 후 계정 ID를 제대로 비교하지 못해서 내 계정이 아닐 때 나오는 팔로우 버튼이 뜨던 문제를 수정했습니다.
=> Fix: 프로필 수정 후에도 기존 accountname과 비교하고 있던 오류 수정

src/components/modules/PostCard/PostCard.jsx, src/components/modules/PostCard/PostCardAPI.js, src/components/organisms/ProductList/ProductList.jsx, src/components/organisms/ProductList/ProductListAPI.js, src/pages/ProfilePage/ProfilePage.jsx
- #11 에서 상품이나 게시글을 삭제했을 때 프로필 페이지가 업데이트되지 않던 문제를 수정했습니다. (API 내에서 토큰 받아오는 코드를 수정해서 해결)
- isDeleteProduct, isDeletePost를 사용하지 않아도 업데이트되도록 변경하였습니다.
=> Fix: 상품/게시글 삭제 후 프로필 페이지가 업데이트되지 않던 문제 수정

src/common/FollowUser.js, src/common/UnfollowUser.js, src/components/modules/ProfileButton/ProfileButton.jsx, src/components/modules/UserFollow/UserFollow.jsx, src/components/organisms/FollowList/FollowList.jsx, src/components/organisms/UserProfile/UserProfile.jsx, src/pages/FollowerPage/FollowerPage.jsx, src/pages/FollowingPage/FollowingPage.jsx
- #161 을 완료했습니다.
- 팔로우/언팔로우하면 프로필 페이지, 팔로워/팔로잉 페이지에 바로 반영됩니다.
- 팔로워/팔로잉 리스트에 현재 로그인된 계정이 있을 경우 버튼이 출력되지 않습니다.
- 프로필 페이지와 팔로워/팔로잉 페이지 총 세 개에서 같은 함수를 사용하기 때문에 common 폴더 안에 넣어주었습니다.
- #171 을 머지해야 바뀌는 게 제대로 보입니다.
=> Feat: 팔로우/언팔로우 기능 추가

src/components/modules/UserProfileBox/userProfileBox.module.css
- #11 이 모바일(갤럭시 폴드)에서는 사진과 팔로워/팔로잉 수 사이의 간격이 너무 멀어 잘리기 때문에 미디어 쿼리를 추가하였습니다.
수정 전
수정 후
=> Design: 모바일에서 프로필 사진과 팔로워/팔로잉 수 사이의 간격이 줄어들게 수정

src/components/atoms/ImageBox/ImageBox.jsx, src/components/modules/PostCard/postCard.module.css
- #166 
- Image box 경로 잘못되었을 경우 엑박 대신 대체이미지를 넣도록 하였습니다. 
- 추가로, PostCard 컴포넌트에서도 글이 길어질 경우 화면을 뚫는 경우가 있어서 해결해주었습니다. 
- 이미지 경로 예외처리 함수를 만들다가.. 예외처리 경우의 수가 너무 많아서 경로를 불러올 수 없는 경우 모두 대체이미지를 넣도록 설정해주었습니다. 
- 이미지는 임시로 넣어놓았는데, 저번에 혜원님이 만드셨던 울고있는 고양이로나 다른걸로 대체해도 좋을것 같아요!!ㅎㅎㅎ
=> Fix: Image box 경로 잘못되었을 경우 대체이미지 넣기 

src/components/atoms/NavItem/NavItem.jsx, src/pages/ProfilePage/ProfilePage.jsx, src/pages/ProfilePage/ProfilePageAPI.js
- #162 를 해결하여 존재하지 않는 유저의 프로필 페이지로 이동하면 에러 페이지를 보여주도록 했습니다.
- 정상작동하긴 하는데, 내비게이션 바에서 프로필 버튼을 눌렀을 때는 왠지 모르게 안 먹히더라고요. 새로고침하면 잘 되는데... 추후에 더 수정해 보겠습니다! #186 
- 우선은 에러 페이지 컴포넌트 자체를 보여주고 있는데, /notfound라던가 url을 하나 정해서 거기로 리디렉션해주는 게 나을까요?
=> Fix: 존재하지 않는 사용자일 경우 에러 페이지를 보여주도록 수정

src/components/modules/LoginForm/LoginForm.jsx, src/pages/RegisterPage/RegisterPage.jsx
- #12 에서 #177 를 해결하였습니다.
- LoginForm이 이메일 인풋, 비밀번호 인풋이라 로그인, 회원가입에서 공유하는 컴포넌트였는데 비밀번호 확인이 생기면서 폼이 달라지게 돼서 같은 컴포넌트로 두는 게 맞는지는 모르겠습니다... 하지만 이미 고치기엔 늦은 거 같아서 그냥 기존 컴포넌트에 비밀번호 확인 인풋을 추가했습니다
=> Feat: 회원 가입 페이지에 비밀번호 확인 추가

src/components/atoms/NavItem/NavItem.jsx
- #186 을 수정하였습니다.
- [페이지 새로고침 메서드](https://stackoverflow.com/questions/53420677/react-link-doesnt-refresh-the-page)
- [url의 파라미터만 다른 경우 새로고침되지 않는 문제](https://developpaper.com/question/why-does-react-router-jump-in-the-case-of-the-same-url-and-different-parameters-but-does-not-refresh-the-page/)
- 이슈에 설명된 것처럼 타인의 프로필에서 내 프로필로 이동할 때는 로딩 컴포넌트도 뜨지 않고 버벅이면서 바뀝니다. 도저히 원인을 모르겠어서 프로필일 경우에만 `window.location.reload()` 를 이용하여 새로고침을 한 번 더 해주도록 하였습니다.
=> Fix: 타인의 프로필 페이지에서 하단 바의 프로필 버튼을 눌렀을 때의 오류 수정

src/common/checkValid.js, src/components/molecules/LoginForm/LoginForm.jsx, src/pages/SplashPage/SplashPage.jsx
- #145 를 로그인 시 하도록 수정하였습니다.
- #1 에서 쓸데 없이 setUser를 쓰고 있던 부분을 삭제하였습니다.
- 사실 토큰 유효성 검사를 대체 언제 해야 하는 건지 애매해서 미루고 있었는데, (최초 접속 페이지의 경우라면) 토큰을 받아 와서 컨텍스트에 저장할 때 검사하는 것도 괜찮을 것 같다는 답변을 받았습니다.
**원래라면 api 요청에서 토큰이 필요할 때마다 검증하는 것이 적절하다고 하셨습니다.**
- 저는 로그인 시 로그인에 성공하면 세션 스토리지에 정보를 저장하는 동시에 컨텍스트에 저장하도록 코드를 작성했고, 나머지 페이지는 컨텍스트의 정보를 받아오고 있기 때문에 로그인 시에만 검사하고 토큰이 검증되었을 때만 세션스토리지와 컨텍스트에 저장하도록 하였습니다.
(사실 로그인 시에 받아오는 토큰은 잘못되거나 만료될 일이 없으니 이게 맞나 싶기도 합니다)
- 토큰이 유효성 검사에 통과되지 않았을 경우에는 어떤 동작을 하게 해야 하는지 몰라서 따로 else로 적어주지 못했습니다.
- 파일명이 checkValid인 이유는 토큰 검증 외에 이메일, 계정 ID 검증 부분도 이 파일로 옮기려고 하기 때문입니다.
=> Fix: 컨텍스트에 정보 저장하기 전 토큰 검증하도록 수정

src/components/molecules/PostCard/postCard.module.css
- #159 를 프로필 사진 크기에 맞게 수정하였습니다.
- 간단해서 그냥 제가 고쳤는데 괜찮으시죠?
=> Design: PostCard 컴포넌트의 프로필 사진 링크 범위 수정

src/App.jsx, src/common/checkValid.js
- close #210 
토큰이 없거나 검증이 안 되었을 때, 스플래시, 로그인, 회원가입 페이지를 제외한 페이지에서 confirm 창이 출력되도록 수정하였습니다.
확인 버튼을 누르면 로그인 페이지로, 취소 버튼을 누르면 스플래시 페이지로 이동하게 하였습니다.
- [리액트에서 현재 페이지 pathname 가져오기](https://stackoverflow.com/questions/42253277/react-router-v4-how-to-get-current-route)
- [alert, prompt, confirm이 두 번 출력되는 이유](https://stackoverflow.com/questions/66263996/react-app-my-alert-window-is-showing-up-twice)
- 레퍼런스에서 적은 것처럼 `React.StrictMode`가 있으면 렌더링을 두 번 해서 알림창이 두 번 뜨게 된다고 합니다. 그래서 우선 index.js의 strictmode 부분을 주석처리했는데, 혹시 해결 방안을 찾으면 다시 strictmode를 살리겠습니다!
=> Fix: 토큰 검증이 안 되었을 때 confirm 창 출력되게 수정

.firebaserc, .github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml, firebase.json, src/common/FollowUser.js, src/common/UnfollowUser.js, src/components/molecules/ProfileButton/ProfileButton.jsx, src/components/molecules/UserFollow/UserFollow.jsx, src/components/organisms/UserProfile/UserProfile.jsx, src/pages/FollowerPage/FollowerPage.jsx, src/pages/FollowerPage/FollowerPageAPI.js, src/pages/FollowingPage/FollowingPage.jsx, src/pages/FollowingPage/FollowingPageAPI.js, src/pages/ProfilePage/ProfilePage.jsx
- 팔로우/언팔로우 시 컴포넌트가 바뀌는 부분을 수정했습니다.
(`[isChangeFollow, setChangeFollow]` state를 없애고 useEffect 삭제, 핸들러 함수 분리)
- 팔로워, 팔로잉 리스트를 받아오는 함수 안에서 setState하는 대신 result를 리턴하여 해당 컴포넌트에서 setState하도록 변경하였습니다.
=> Refactor: 팔로우/언팔로우 과정 수정

firebase.json
- 깃허브 액션 설정하다가 기존의 설정이 누락되어 배포가 제대로 되고 있지 않던 점을 수정했습니다.
(중복 때문에 프로젝트 이름(game-us-404)과 사이트 이름(gameus)을 다르게 해 놓았었는데, 설정하면서 `site` 부분이 날아가서 프로젝트 이름의 도메인으로 잘못 배포되고 있었습니다.)
=> Fix: 사이트 이름으로 deploy되도록 파이어베이스 설정 파일 수정
